trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: buildstage
  jobs:
  - job: firstjob
    steps:
    - bash: echo build first job
- stage: devstage
  dependsOn: buildstage
  jobs:
  - job: secondjob
    steps:
    - bash: echo build second job
- stage: prodstage
  dependsOn:
  - devstage
  - buildstage
  jobs:
  - job: thirdjob
    steps:
    - bash: echo build third job
- stage: packstage
  dependsOn:
  - devstage
  - buildstage
  - prodstage
  jobs:
  - job: thirdjob
    steps:
    - bash: echo build third job