trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: buildstage
  jobs:
  - job: firstjob
    steps:
    - bash: echo build first job
- stage: devstage
  jobs:
  - job: secondjob
    steps:
    - bash: echo build second job
- stage: prodstage
  jobs:
  - job: thirdjob
    steps:
    - bash: echo build third job